to-edictor:
	edictor wordlist --name=blumpanotacana --data=../cldf/cldf-metadata.json --preprocessing=fullproc.py --addon="cognacy:cog,language_subgroup:subgroup"

wordlist-auto:
	edictor wordlist --name=bpt-auto --data=../cldf/cldf-metadata.json --preprocessing=autocogid.py --addon="cognacy:cogid","cogids:cogids"
