to-edictor:
	edictor wordlist --name=blumpanotacana --data=../cldf/cldf-metadata.json --preprocessing=realign.py --addon="language_subgroup:subgroup","cognacy:cogid","partial_cognacy:cogids","morphemes:morphemes","borrowing:borrowing","comment:note"

wordlist-auto:
	edictor wordlist --name=bpt-auto --data=../cldf/cldf-metadata.json --preprocessing=autocogid.py --addon="cognacy:cogid","cogids:cogids"
